---
kind: pipeline
name: default

trigger:
  branch: master

steps:
  - name: test
    image: golangci/golangci-lint:v1.38.0-alpine
    commands:
      - golangci-lint run --timeout=5m
      - go test -cover ./...
