---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: test
    image: golangci/golangci-lint:v1.38.0-alpine
    commands:
      - golangci-lint run --timeout=5m
      - go test -cover ./...

  - name: publish
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/mongodb/drone-validation
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
      event:
        - push

  - name: publish_tag
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/mongodb/drone-validation
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - ${DRONE_TAG}
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
      event:
        - tag
