---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: test
    image: golang:1.16
    commands:
      - go vet ./...
      - go test ./...

  - name: publish
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/mongodb-labs/drone-validation
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
      event:
        - push

  - name: publish_tag
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/mongodb-labs/drone-validation
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - ${DRONE_TAG}
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
      event:
        - tag
