kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang
  commands:
  - go build
  - go test ./...

- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    repo: registry.example.com/drone-validation
    registry: registry.example.com
    insecure: true
