---
replicaCount: 1
ingress:
  enabled: false
image:
  repository: registry.example.com/drone-validation
  tag: latest
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
env:
  DRONE_DEBUG: true
  DRONE_SECRET: bea26a2221fd8090ea38720fc445eae7
  DRONE_POLICY_PATH: "/go/src/app/policy"
